-- INSERTS para tabla clasificacion

INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (1, 'Abundance Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (2, 'Acorn Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (3, 'Alpha Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (4, 'Angler Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (5, 'Ant Pit Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (6, 'Anteater Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (7, 'Antenna Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (8, 'Aquamouse Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (9, 'Aquarabbit Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (10, 'Arm Thrust Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (11, 'Armor Bird Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (12, 'Armor Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (13, 'Arrow Quill Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (14, 'Artificial Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (15, 'Astral Body Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (16, 'Atrocious Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (17, 'Attaching Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (18, 'Aura Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (19, 'Aurora Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (20, 'Automaton Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (21, 'Avianoid Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (22, 'Axe Jaw Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (23, 'Bagworm Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (24, 'Ball Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (25, 'Ball Roll Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (26, 'Ball Whale Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (27, 'Balloon Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (28, 'Barnacle Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (29, 'Barrier Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (30, 'Bash Buffalo Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (31, 'Bat Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (32, 'Battery Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (33, 'Beak Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (34, 'Beaver Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (35, 'Beckon Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (36, 'Bee Fly Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (37, 'Beehive Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (38, 'Bell Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (39, 'Big Boss Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (40, 'Big Eater Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (41, 'Big Horn Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (42, 'Big Jaw Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (43, 'Big Voice Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (44, 'Big-Hearted Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (45, 'Bird Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (46, 'Bite Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (47, 'Bivalve Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (48, 'Blade Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (49, 'Blade Quill Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (50, 'Blast Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (51, 'Blast Turtle Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (52, 'Blaze Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (53, 'Blazing Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (54, 'Blimp Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (55, 'Bloom Sickle Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (56, 'Blossom Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (57, 'Bolt Strike Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (58, 'Bone Keeper Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (59, 'Bone Vulture Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (60, 'Bonsai Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (61, 'Bounce Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (62, 'Boundary Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (63, 'Bouquet Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (64, 'Boxing Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (65, 'Bright Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (66, 'Bronze Bell Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (67, 'Bronze Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (68, 'Brutal Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (69, 'Brutal Star Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (70, 'Bubble Frog Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (71, 'Bubble Jet Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (72, 'Bud Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (73, 'Bug Catcher Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (74, 'Bugle Beak Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (75, 'Bulb Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (76, 'Butterfly Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (77, 'Cactus Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (78, 'Candle Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (79, 'Cannon Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (80, 'Carefree Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (81, 'Caring Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (82, 'Cat Ferret Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (83, 'Catty Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (84, 'Cavalry Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (85, 'Cave Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (86, 'Cavern Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (87, 'Cell Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (88, 'Centipede Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (89, 'Cerebral Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (90, 'Cheering Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (91, 'Cherry Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (92, 'Chick Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (93, 'Chill Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (94, 'Chimp Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (95, 'Chinchilla Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (96, 'Clamping Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (97, 'Clap Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (98, 'Classy Cat Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (99, 'Clay Doll Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (100, 'Clear Wing Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (101, 'Coal Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (102, 'Cobra Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (103, 'Coconut Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (104, 'Cocoon Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (105, 'Coffin Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (106, 'Collective Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (107, 'Color Swap Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (108, 'Colossal Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (109, 'Colt Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (110, 'Compass Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (111, 'Compressed Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (112, 'Constraint Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (113, 'Continent Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (114, 'Coral Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (115, 'Cotton Bird Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (116, 'Cotton Candy Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (117, 'Cotton Puff Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (118, 'Cottonweed Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (119, 'Courting Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (120, 'Cricket Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (121, 'Cruel Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (122, 'Crystallizing Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (123, 'Curlipede Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (124, 'Cyclone Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (125, 'DNA Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (126, 'Dancing Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (127, 'Dark Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (128, 'Darkness Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (129, 'Daunting Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (130, 'Deceiver Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (131, 'Deep Black Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (132, 'Deep Sea Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (133, 'Delivery Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (134, 'Desert Croc Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (135, 'Despot Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (136, 'Destruction Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (137, 'Devious Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (138, 'Diapered Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (139, 'Digging Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (140, 'Disaster Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (141, 'Discharge Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (142, 'Discipline Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (143, 'Disguise Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (144, 'Diving Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (145, 'Donkey Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (146, 'Dopey Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (147, 'Draft Horse Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (148, 'Dragon Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (149, 'Drawn Sword Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (150, 'Dream Eater Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (151, 'Drill Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (152, 'Drowsing Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (153, 'Duck Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (154, 'Eaglet Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (155, 'Egg Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (156, 'Elder Tree Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (157, 'EleFish Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (158, 'EleSpider Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (159, 'EleSquirrel Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (160, 'Electric Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (161, 'Electrified Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (162, 'Emanation Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (163, 'Ember Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (164, 'Embrace Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (165, 'Emotion Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (166, 'Emperor Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (167, 'Endurance Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (168, 'Eon Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (169, 'Eruption Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (170, 'Evolution Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (171, 'Eyeball Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (172, 'Face Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (173, 'Fairy Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (174, 'Fang Scorp Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (175, 'Fang Snake Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (176, 'Feeling Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (177, 'Fire Cat Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (178, 'Fire Horse Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (179, 'Fire Mouse Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (180, 'Fire Pig Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (181, 'Firefly Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (182, 'First Bird Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (183, 'Fish Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (184, 'Five Star Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (185, 'Fixation Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (186, 'Flailing Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (187, 'Flame Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (188, 'Flash Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (189, 'Float Whale Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (190, 'Floating Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (191, 'Flower Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (192, 'Flowering Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (193, 'Flycatcher Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (194, 'Flyscorpion Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (195, 'Forbidden Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (196, 'Forest Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (197, 'Formidable Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (198, 'Fossil Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (199, 'Fox Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (200, 'Fragrance Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (201, 'Freeze Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (202, 'Freezing Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (203, 'Fresh Snow Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (204, 'Frog Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (205, 'Frosted Tree Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (206, 'Fruit Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (207, 'Garden Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (208, 'Gas Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (209, 'Gear Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (210, 'Generator Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (211, 'Genetic Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (212, 'Geyser Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (213, 'Gleam Eyes Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (214, 'Glowing Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (215, 'Gnash Teeth Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (216, 'Goldfish Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (217, 'Grass Monkey Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (218, 'Grass Quill Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (219, 'Grass Snake Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (220, 'Grassland Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (221, 'Gratitude Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (222, 'Gripper Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (223, 'Grove Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (224, 'Guts Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (225, 'Hairy Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (226, 'Handstand Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (227, 'Happiness Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (228, 'Hard Scale Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (229, 'Hard Shell Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (230, 'Head Butt Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (231, 'Hearing Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (232, 'Heavyweight Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (233, 'Heel Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (234, 'Herb Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (235, 'Hermit Crab Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (236, 'Hibernator Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (237, 'High Temp Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (238, 'Hippo Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (239, 'Hoodlum Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (240, 'Hostile Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (241, 'Howitzer Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (242, 'Humanshape Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (243, 'Humming Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (244, 'Hypnosis Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (245, 'Ice Break Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (246, 'Ice Chunk Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (247, 'Iceberg Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (248, 'Icy Snow Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (249, 'Illuminating Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (250, 'Illusion Fox Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (251, 'Imitation Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (252, 'Insect Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (253, 'Intertwining Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (254, 'Intimidation Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (255, 'Irate Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (256, 'Iron Ant Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (257, 'Iron Armor Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (258, 'Iron Ball Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (259, 'Iron Claw Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (260, 'Iron Leg Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (261, 'Iron Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (262, 'Iron Snake Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (263, 'Iron Will Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (264, 'Jellyfish Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (265, 'Jet Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (266, 'Jewel Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (267, 'Jolly Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (268, 'Jubilee Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (269, 'Judo Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (270, 'Junkivore Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (271, 'Karate Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (272, 'Key Ring Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (273, 'Kicking Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (274, 'Kiss Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (275, 'Kite Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (276, 'Kitten Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (277, 'Knowledge Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (278, 'Lamp Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (279, 'Land Shark Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (280, 'Land Snake Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (281, 'Land Spirit Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (282, 'Larva Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (283, 'Launch Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (284, 'Lava Dome Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (285, 'Lava Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (286, 'Lazy Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (287, 'Leaf Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (288, 'Leaf-Wrapped Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (289, 'Legendary Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (290, 'Licking Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (291, 'Life Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (292, 'Light Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (293, 'Lightning Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (294, 'Lion Cub Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (295, 'Lissome Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (296, 'Little Bear Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (297, 'Little Bird Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (298, 'Live Coal Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (299, 'Lizard Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (300, 'Loitering Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (301, 'Lonely Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (302, 'Long Body Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (303, 'Long Leg Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (304, 'Long Neck Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (305, 'Long Nose Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (306, 'Long Tail Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (307, 'Longevity Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (308, 'Lookout Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (309, 'Loud Noise Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (310, 'Loyal Dog Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (311, 'Lunar Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (312, 'Luring Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (313, 'Mach Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (314, 'Magical Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (315, 'Magnet Area Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (316, 'Magnet Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (317, 'Manipulate Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (318, 'Mantis Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (319, 'Mantle Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (320, 'Marionette Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (321, 'Martial Arts Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (322, 'Meditate Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (323, 'Mega Fire Pig Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (324, 'Megapede Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (325, 'Megaton Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (326, 'Melody Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (327, 'Meringue Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (328, 'Meteor Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (329, 'Meteorite Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (330, 'Milk Cow Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (331, 'Mime Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (332, 'Mischief Pokémon (Confined)Djinn Pokémonn (Unbound)');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (333, 'Mitosis Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (334, 'Mock Kelp Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (335, 'Mold Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (336, 'Mole Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (337, 'Moone Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (338, 'Moonlight Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (339, 'Moth Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (340, 'Mount Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (341, 'Mouse Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (342, 'Mud Fish Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (343, 'Multiplying Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (344, 'Muscular Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (345, 'Mushroom Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (346, 'Music Note Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (347, 'Mysterious Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (348, 'Mystic Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (349, 'Nebula Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (350, 'Neon Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (351, 'New Species Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (352, 'Ninja Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (353, 'Numb Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (354, 'Nurturing Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (355, 'Ogre Darner Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (356, 'Ogre Scorp Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (357, 'Old Shrimp Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (358, 'Order Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (359, 'Ore Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (360, 'Overturning Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (361, 'Owl Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (362, 'Painter Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (363, 'Paleozoic Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (364, 'Parasite Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (365, 'Parent Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (366, 'Patient Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (367, 'Penguin Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (368, 'Perfume Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (369, 'Pig Monkey Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (370, 'Pig Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (371, 'Pincer Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (372, 'Pitch-Black Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (373, 'Placid Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (374, 'Plasma Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (375, 'Plate Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (376, 'Playful Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (377, 'Playhouse Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (378, 'Plump Mouse Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (379, 'Poison Bag Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (380, 'Poison Bee Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (381, 'Poison Gas Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (382, 'Poison Moth Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (383, 'Poison Pin Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (384, 'Polka Dot Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (385, 'Pond Skater Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (386, 'Poodle Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (387, 'Pop Star Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (388, 'Posy Picker Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (389, 'Predator Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (390, 'Prim Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (391, 'Prism Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (392, 'Protostar Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (393, 'Prototurtle Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (394, 'Proud Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (395, 'Psi Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (396, 'Pumpkin Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (397, 'Punching Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (398, 'Puppet Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (399, 'Puppy Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (400, 'Rabbit Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (401, 'Rainbow Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (402, 'Regal Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (403, 'Rendezvous Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (404, 'Renegade Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (405, 'Requiem Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (406, 'Restraint Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (407, 'Revolving Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (408, 'River Crab Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (409, 'Rock Head Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (410, 'Rock Inn Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (411, 'Rock Peak Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (412, 'Rock Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (413, 'Rock Skin Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (414, 'Rock Snake Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (415, 'Rogue Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (416, 'Roly-Poly Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (417, 'Royal Heir Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (418, 'Royal Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (419, 'Royal Sword Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (420, 'Ruffian Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (421, 'Rush Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (422, 'Sage Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (423, 'Sand Castle Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (424, 'Sand Heap Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (425, 'Savage Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (426, 'Scale Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (427, 'Scaly Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (428, 'Scarecrow Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (429, 'Scarf Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (430, 'Scatterdust Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (431, 'Scorching Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (432, 'Scorpion Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (433, 'Scout Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (434, 'Scratch Cat Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (435, 'Screech Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (436, 'Scuffle Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (437, 'Sea Basin Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (438, 'Sea Creeper Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (439, 'Sea Cucumber Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (440, 'Sea Drifter Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (441, 'Sea Lily Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (442, 'Sea Lion Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (443, 'Sea Otter Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (444, 'Sea Slug Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (445, 'Sea Weasel Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (446, 'Seafaring Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (447, 'Seagull Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (448, 'Season Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (449, 'Seed Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (450, 'Sewing Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (451, 'Shadow Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (452, 'Sharp Blade Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (453, 'Sharp Claw Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (454, 'Shed Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (455, 'Shedding Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (456, 'Shell Out Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (457, 'Shellfish Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (458, 'Shield Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (459, 'Sickle Grass Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (460, 'Single Bloom Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (461, 'Singlehorn Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (462, 'Skunk Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (463, 'Sky High Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (464, 'Sky Squirrel Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (465, 'Slacker Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (466, 'Sleeping Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (467, 'Sludge Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (468, 'Small Fry Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (469, 'Snail Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (470, 'Snake Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (471, 'Snow Hat Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (472, 'Snow Land Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (473, 'Snowstorm Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (474, 'Soft Tissue Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (475, 'Soloist Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (476, 'Sound Wave Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (477, 'South Sea Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (478, 'Spark Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (479, 'Spatial Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (480, 'Spike Ball Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (481, 'Spikes Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (482, 'Spiky Nut Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (483, 'Spiny Armor Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (484, 'Spiral Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (485, 'Spirit Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (486, 'Spitfire Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (487, 'Spot Panda Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (488, 'Spray Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (489, 'Stag Beetle Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (490, 'Stagbeetle Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (491, 'Stakeout Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (492, 'Star Shape Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (493, 'Starling Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (494, 'Starshape Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (495, 'Steam Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (496, 'Stomach Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (497, 'Stone Home Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (498, 'String Spit Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (499, 'Strong Arm Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (500, 'Stump Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (501, 'Subterrene Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (502, 'Sun Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (503, 'Sunne Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (504, 'Superpower Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (505, 'Swallow Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (506, 'Swine Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (507, 'Swollen Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (508, 'Sword Blade Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (509, 'Sword Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (510, 'Symbol Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (511, 'Synthetic Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (512, 'Tadpole Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (513, 'Teamwork Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (514, 'Temporal Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (515, 'Tender Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (516, 'Thorn Monkey Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (517, 'Thorn Pod Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (518, 'Thorn Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (519, 'Thorn Seed Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (520, 'Thunder Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (521, 'Thunderbolt Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (522, 'Tiger Cat Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (523, 'Time Travel Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (524, 'Tiny Bee Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (525, 'Tiny Bird Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (526, 'Tiny Leaf Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (527, 'Tiny Mouse Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (528, 'Tiny Pigeon Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (529, 'Tiny Racoon Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (530, 'Tiny Robin Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (531, 'Tiny Turtle Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (532, 'TinySwallow Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (533, 'Torch Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (534, 'Toxic Lizard Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (535, 'Toxic Mouth Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (536, 'Trainee Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (537, 'Transform Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (538, 'Transport Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (539, 'Trap Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (540, 'Trash Bag Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (541, 'Trash Heap Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (542, 'Tricky Fox Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (543, 'Triple Bird Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (544, 'Tundra Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (545, 'Turn Tail Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (546, 'Turtle Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (547, 'Tusk Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (548, 'Twin Bird Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (549, 'Twin Tusk Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (550, 'Two-Handed Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (551, 'Valiant Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (552, 'Vast White Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (553, 'Verdant Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (554, 'Vibration Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (555, 'Victory Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (556, 'Vine Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (557, 'Virtual Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (558, 'Volcano Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (559, 'Water Bird Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (560, 'Water Bubble Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (561, 'Water Fish Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (562, 'Water Gun Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (563, 'Water Weed Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (564, 'Weather Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (565, 'Weed Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (566, 'Whiskers Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (567, 'Whisper Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (568, 'White Bird Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (569, 'Wickid Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (570, 'Wild Bull Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (571, 'Wild Duck Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (572, 'Wild Monkey Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (573, 'Wild Pigeon Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (574, 'Willpower Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (575, 'Wily Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (576, 'Wind Chime Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (577, 'Windveiled Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (578, 'Wing Fish Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (579, 'Wish Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (580, 'Wolf Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (581, 'Wood Gecko Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (582, 'Woodpecker Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (583, 'Wool Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (584, 'Woolly Crab Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (585, 'Worm Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (586, 'Wrestling Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (587, 'Young Fowl Pokémon');
INSERT INTO clasificacion (id_clasificacion, descripcion) VALUES (588, 'Zen Charm Pokémon');
